<project> ::= <project_prop> <precip>* <basin>* <control>*

<project_prop> ::= <project_name> <desc> <version> <sep> <dss> <zone> <end>
<project_name> ::= <project_name_l> <project_name_v> "\n"
<project_name_l> ::= "Project: "
<project_name_v> ::= <name>
<desc> ::= <desc_l> <desc_v> "\n"
<desc_l> ::= "     Description: "
<desc_v> ::= <name_opt>
<version> ::= <version_l> <version_v> "\n"
<version_l> ::= "     Version: "
<version_v> ::= "4." ([0-9] | ("1" [0-9]) | ("2" [0-9]) | ("3" [0-9]) | ("4" [0-9]) | ("5" [0-9]) | ("6" [0-9]) | ("7" [0-9]) | ("8" [0-9]) | ("9" [0-9]))
<sep> ::= <sep_l> <sep_v> "\n"
<sep_l> ::= "     Filepath Separator: "
<sep_v> ::= "/" | "\"
<dss> ::= <dss_l> <dss_v> "\n"
<dss_l> ::= "     DSS File Name: "
<dss_v> ::= <name> ".dss"
<zone> ::= <zone_l> <zone_v> "\n"
<zone_l> ::= "     Time Zone ID: "
<zone_v> ::= "America/Chicago"

<precip> ::= <precip_name> <precip_file> <precip_desc> <precip_mod_date> <precip_mod_time> <end>
<precip_name> ::= <precip_name_l> <precip_name_v> "\n"
<precip_name_l> ::= "Precipitation: "
<precip_name_v> ::= <name>
<precip_file> ::= <precip_file_l> <precip_file_v> "\n"
<precip_file_l> ::= "     Filename: "
<precip_file_v> ::= <name> ".met"
<precip_desc> ::= <precip_desc_l> <precip_desc_v> "\n"
<precip_desc_l> ::= "     Description: "
<precip_desc_v> ::= <name_opt>
<precip_mod_date> ::= <precip_mod_date_l> <precip_mod_date_v> "\n"
<precip_mod_date_l> ::= "     Last Modified Date: "
<precip_mod_date_v> ::= <mod_date>
<precip_mod_time> ::= <precip_mod_time_l> <precip_mod_time_v> "\n"
<precip_mod_time_l> ::= "     Last Modified Time: "
<precip_mod_time_v> ::= <mod_time>

<basin> ::= <basin_name> <basin_file> <basin_desc> <basin_mod_date> <basin_mod_time> <end>
<basin_name> ::= <basin_name_l> <basin_name_v> "\n"
<basin_name_l> ::= "Basin: "
<basin_name_v> ::= <name>
<basin_file> ::= <basin_file_l> <basin_file_v> "\n"
<basin_file_l> ::= "     Filename: "
<basin_file_v> ::= <name> ".basin"
<basin_desc> ::= <basin_desc_l> <basin_desc_v> "\n"
<basin_desc_l> ::= "     Description: "
<basin_desc_v> ::= <name_opt>
<basin_mod_date> ::= <basin_mod_date_l> <basin_mod_date_v> "\n"
<basin_mod_date_l> ::= "     Last Modified Date: "
<basin_mod_date_v> ::= <mod_date>
<basin_mod_time> ::= <basin_mod_time_l> <basin_mod_time_v> "\n"
<basin_mod_time_l> ::= "     Last Modified Time: "
<basin_mod_time_v> ::= <mod_time>

<control> ::= <control_name> <control_file> <control_desc> <end>
<control_name> ::= <control_name_l> <control_name_v> "\n"
<control_name_l> ::= "Control: "
<control_name_v> ::= <name>
<control_file> ::= <control_file_l> <control_file_v> "\n"
<control_file_l> ::= "     Filename: "
<control_file_v> ::= <name> ".control"
<control_desc> ::= <control_desc_l> <control_desc_v> "\n"
<control_desc_l> ::= "     Description: "
<control_desc_v> ::= <name_opt>

<mod_time> ::= <hour> ":" <minute>
<hour> ::= ("0" [0-9]) | ("1" [0-9]) | ("2" [0-3])
<minute> ::= ("0" [0-9]) | ("1" [0-9]) | ("2" [0-9]) | ("3" [0-9]) | ("4" [0-9]) | ("5" [0-9])
<mod_date> ::= <day> " " <month> " " <year>
<day> ::= ("0" [0-9]) | ("1" [0-9]) | ("2" [0-9]) | ("3" [0-1])
<month> ::= "January" | "February" | "March" | "April" | "May" | "June" | "July" | "August" | "September" | "October" | "November" | "December"
<year> ::= ("19" (("7" [0-9]) | ("8" [0-9]) | ("9" [0-9]))) | ("2" [0-9] [0-9] [0-9])
<name> ::= ( [0-9] | [a-z] | [A-Z] | "_" | " " | "-" )+
<name_opt> ::= ( [0-9] | [a-z] | [A-Z] | "_" | " " | "-" )*
<end> ::= "End:" "\n" "\n"
<bool_str> ::= "No" | "Yes"
